/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

DROP DATABASE IF EXISTS `me_api`;
CREATE DATABASE IF NOT EXISTS `me_api` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `me_api`;

DROP TABLE IF EXISTS `c_user`;
CREATE TABLE IF NOT EXISTS `c_user` (
  `RECID` varchar(15) NOT NULL DEFAULT '',
  `FULL_NAME` varchar(50) DEFAULT '',
  `SIGNON_NAME` varchar(30) DEFAULT '',
  `DEPARTMENT` varchar(5) DEFAULT '',
  `COMPANY_CODE` varchar(15) DEFAULT '',
  `DEPARTMENT_CODE` varchar(5) DEFAULT '',
  `PROFILE_START_DATE` varchar(10) DEFAULT '',
  `PROFILE_END_DATE` varchar(10) DEFAULT '',
  `PROFILE_START_TIME` varchar(6) DEFAULT '',
  `PROFILE_END_TIME` varchar(6) DEFAULT '',
  `STATUS` varchar(1) DEFAULT '',
  `USER_ROLE` varchar(5) DEFAULT '',
  `USER_FUNCTION` varchar(15) DEFAULT '',
  `COMPANY_ACCESS` varchar(50) DEFAULT '',
  `COMPANY_RESTRICT` varchar(50) DEFAULT '',
  `USER_TYPE` varchar(15) DEFAULT '',
  `ATTEMP` varchar(1) DEFAULT '',
  `PASSWORD` text DEFAULT '',
  `TOOKEN` text DEFAULT '',
  `CURRENT_NO` varchar(4) DEFAULT '',
  `RECORD_STATUS` varchar(3) DEFAULT '',
  `OVERRIDE` varchar(2) DEFAULT '',
  `CO_CODE` varchar(10) DEFAULT '',
  `INPUTTER` varchar(15) DEFAULT '',
  `DATETIME1` varchar(20) DEFAULT '',
  `AUTHORISER` varchar(15) DEFAULT '',
  `DATETIME2` varchar(20) DEFAULT '',
  PRIMARY KEY (`RECID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `c_user`;
INSERT INTO `c_user` (`RECID`, `FULL_NAME`, `SIGNON_NAME`, `DEPARTMENT`, `COMPANY_CODE`, `DEPARTMENT_CODE`, `PROFILE_START_DATE`, `PROFILE_END_DATE`, `PROFILE_START_TIME`, `PROFILE_END_TIME`, `STATUS`, `USER_ROLE`, `USER_FUNCTION`, `COMPANY_ACCESS`, `COMPANY_RESTRICT`, `USER_TYPE`, `ATTEMP`, `PASSWORD`, `TOOKEN`, `CURRENT_NO`, `RECORD_STATUS`, `OVERRIDE`, `CO_CODE`, `INPUTTER`, `DATETIME1`, `AUTHORISER`, `DATETIME2`) VALUES
	('U00000', 'SYSYEM OWNER', 'SYSTEM', '1', 'KH0010001', '1', '20230101', '23001231', '0000', '2359', 'A', 'SYSTE', 'S I A 2 D R V P', 'ALL', '', 'SUPER.USER', '', '12345678', '', '1', '', '', 'KH0010001', 'U00000', '20230101000001', 'U00000', '20230101000001');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
